"""Judge worker, executed by AdaMAST's OWN interpreter -- never imported here.

Why a separate interpreter
--------------------------
``adamast`` is installed as a uv *tool* (its own venv), not as a dependency of
this project, and it stays that way deliberately:

* the certified taxonomy (kappa 0.908, 34 codes -> 22 pruned) was generated by
  that exact install, so judging through the same interpreter guarantees the
  judge assets and code-extraction logic are the ones the taxonomy was
  certified under;
* ``adamast`` pulls ``openai``/``pydantic``/``boto3`` floors into whatever
  environment installs it. The BASELINE seeds run out of this project's venv
  and must stay behaviourally identical (baseline purity), so
  re-resolving that venv mid-experiment is not an acceptable side effect of
  adding the treatment arm.

Constraints this file must satisfy
----------------------------------
It runs under a Python that has ``adamast`` but has **neither ``gepa`` nor
``litellm`` nor this package**. So: standard library plus ``adamast`` only, and
no import from ``gepa_taxonomy``.

Protocol: one JSON request on stdin, one JSON response on stdout.

    in   {taxonomy_path, traces: [<adamast-native record>, ...], provider,
          model, mode, max_trace_chars, max_output_tokens, aws_region,
          aws_profile, allow_review_required}
    out  {diagnoses: [{trace_id, failure_modes, none_apply}, ...],
          usage: {calls, prompt_chars, response_chars, measured}}

Any failure is a non-zero exit with a one-line reason on stderr; the caller
treats that as "no diagnosis" and keeps the run alive.
"""

from __future__ import annotations

import json
import sys
from typing import Any


def _install_usage_probe(usage: dict[str, Any]) -> bool:
    """Wrap the provider so the exact prompt/response sizes can be metered.

    AdaMAST's provider adapters return text only -- no token usage -- so the
    only honest measurement available is character counts at the transport
    boundary. Wrapping ``create_provider`` is the narrowest seam that sees
    every judge call including the JSON-repair retry.

    Returns False if that seam is not present in this AdaMAST version, in which
    case the caller falls back to an estimate from input sizes. Judging must
    not be lost over a metering detail.
    """
    try:
        from adamast.judges import contract
    except Exception:
        return False

    original = getattr(contract, "create_provider", None)
    if original is None:
        return False

    class _Counting:
        def __init__(self, inner: Any) -> None:
            self._inner = inner
            self.name = getattr(inner, "name", "")
            self.model = getattr(inner, "model", "")

        def complete(self, prompt: str, *, system: str = "", response_format: str = "text") -> str:
            usage["prompt_chars"] += len(prompt) + len(system)
            text = self._inner.complete(prompt, system=system, response_format=response_format)
            usage["response_chars"] += len(text or "")
            usage["calls"] += 1
            return text

    def _wrapped(*args: Any, **kwargs: Any) -> Any:
        return _Counting(original(*args, **kwargs))

    contract.create_provider = _wrapped
    return True


def _estimated_chars(payload: dict[str, Any]) -> tuple[int, int]:
    """Fallback sizing when the transport could not be instrumented.

    Deliberately an over-estimate: the taxonomy catalog is counted at its full
    file size and every trace at its full record size. Under-counting judge
    spend would let the dollar-budget stopper fire late, which costs real
    money; over-counting only stops a run slightly early.
    """
    try:
        with open(payload["taxonomy_path"], encoding="utf-8-sig") as fh:
            taxonomy_chars = len(fh.read())
    except OSError:
        taxonomy_chars = 0
    traces = payload.get("traces") or []
    trace_chars = sum(len(json.dumps(t)) for t in traces)
    return taxonomy_chars * len(traces) + trace_chars, 512 * max(1, len(traces))


def main() -> int:
    payload = json.load(sys.stdin)

    usage: dict[str, Any] = {"calls": 0, "prompt_chars": 0, "response_chars": 0}
    usage["measured"] = _install_usage_probe(usage)

    from adamast import judge_traces

    diagnoses = judge_traces(
        payload["taxonomy_path"],
        payload["traces"],
        provider=payload.get("provider"),
        model=payload.get("model"),
        mode=payload.get("mode", "default"),
        max_trace_chars=payload["max_trace_chars"],
        max_output_tokens=payload["max_output_tokens"],
        aws_region=payload.get("aws_region"),
        aws_profile=payload.get("aws_profile"),
        allow_review_required=payload.get("allow_review_required", False),
    )

    if not usage["measured"]:
        usage["prompt_chars"], usage["response_chars"] = _estimated_chars(payload)
        usage["calls"] = len(payload.get("traces") or [])

    out = []
    for diagnosis in diagnoses:
        record = diagnosis.to_dict()
        out.append(
            {
                "trace_id": record.get("trace_id", ""),
                "failure_modes": record.get("failure_modes", []),
                "none_apply": bool(record.get("none_apply", False)),
            }
        )

    json.dump({"diagnoses": out, "usage": usage}, sys.stdout)
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except SystemExit:
        raise
    except Exception as exc:  # one line out, no traceback: the caller logs it
        print(f"{type(exc).__name__}: {exc}", file=sys.stderr)
        raise SystemExit(1) from None
