"""Arm the ``optimize_anything`` evaluator: stock ASI, taxonomy, or score-only.

Why this module exists
----------------------
``optimize_anything`` makes the evaluator's ``side_info`` the *entire* feedback
channel: ``OptimizeAnythingAdapter.make_reflective_dataset`` copies its keys
into the reflection prompt and adds nothing of its own. So the feedback content
is decided by one return statement in user code, and swapping it needs no
library change at all -- unlike our ``TaxonomyAdapter``, which has to wrap an
inner adapter and rewrite its reflective dataset.

That makes this the cleanest available test of the question upstream never
asked. Every published ``optimize_anything`` result compares *their*
hand-authored ASI against an external tool; there is no ablation of the ASI
itself anywhere in the repo or its docs. Three arms answer it:

``STOCK``
    Their ``side_info``, untouched. The hand-authored baseline. Also the arm
    that harvests traces, because a taxonomy has to be generated from
    *something* and it must not be generated from its own arm's output.

``TAXONOMY``
    Their ``side_info`` discarded and replaced by judged failure occurrences.
    Automated, domain-agnostic, generated by AdaMAST from STOCK's traces.

``SCORE_ONLY``
    Nothing but the score-bearing keys. The floor.

SCORE_ONLY is not optional decoration. ``TAXONOMY ~= STOCK`` is only a result
if both are well clear of SCORE_ONLY; without it, a null is indistinguishable
from "the feedback text never mattered and the score did all the work".

The one key that is never dropped
---------------------------------
``side_info["scores"]`` is search machinery, not feedback. Under
``frontier_type="objective"`` the Pareto frontier is built from it (see
``EngineConfig.frontier_type``), so removing it would sabotage candidate
selection and the arms would differ by more than their feedback. It survives
in all three arms; ``PRESERVED_KEYS`` is the explicit list.
"""

from __future__ import annotations

import inspect
import json
import threading
from collections.abc import Callable, Mapping, Sequence
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

from failure_taxonomy.judge import Occurrence
from failure_taxonomy.trace import SegmentedTrace, build_trace

STOCK = "stock"
TAXONOMY = "taxonomy"
SCORE_ONLY = "score"
ARMS = (STOCK, TAXONOMY, SCORE_ONLY)

#: Reflection reads this key. Matches the enrichment path so both designs put
#: failure modes under one name and downstream analysis joins on one field.
FAILURE_MODES_KEY = "failure_modes"

#: Never stripped, in any arm -- see the module docstring. Not a judgement call
#: about usefulness: ``scores`` drives Pareto selection, so dropping it would
#: make the arms differ in their *search*, not just their feedback.
PRESERVED_KEYS = ("scores",)


def _describe(value: Any, limit: int = 4000) -> str:
    """Render one side_info value as text for the judge.

    Values arrive as numpy arrays, nested dicts, None, and strings. ``repr`` is
    used rather than ``json.dumps`` because it never raises on an unserialisable
    object, and a trace that fails to render is a trace the judge silently never
    sees.
    """
    if value is None:
        return ""
    if isinstance(value, str):
        text = value
    else:
        try:
            text = json.dumps(value, default=repr, indent=2)
        except Exception:
            text = repr(value)
    text = text.strip()
    return text if len(text) <= limit else text[:limit].rstrip() + " ... [truncated]"


@dataclass
class TraceSink:
    """Appends one AdaMAST-ready record per evaluation.

    Written by the STOCK arm only. Generating a taxonomy from the taxonomy
    arm's own traces would close a loop that has no fixed point -- the codes
    would describe behaviour the codes themselves produced.
    """

    path: Path
    written: int = 0
    _lock: threading.Lock = field(default_factory=threading.Lock, repr=False)

    def write(self, trace: SegmentedTrace) -> None:
        record = trace.to_generation_record()
        line = json.dumps(record, default=repr)
        with self._lock:
            self.path.parent.mkdir(parents=True, exist_ok=True)
            with self.path.open("a", encoding="utf-8") as handle:
                handle.write(line + "\n")
            self.written += 1


def trace_from_side_info(
    side_info: Mapping[str, Any],
    *,
    trace_id: str,
    task: str = "",
    skip_keys: Sequence[str] = (),
    metadata: Mapping[str, Any] | None = None,
) -> SegmentedTrace:
    """Build a judgeable trace out of one evaluation's ``side_info``.

    ``optimize_anything`` has no module_calls to segment on -- a candidate is a
    text blob, not a pipeline -- so this produces an unsegmented trace and the
    judge routes every occurrence to the single component. That is the honest
    shape for this API rather than a limitation worked around: there genuinely
    is one component when ``seed_candidate`` is a string.

    Score visibility
    ----------------
    ``skip_keys`` drops the dedicated ``scores`` field, so the judge is not
    handed a labelled verdict. It does **not** guarantee the judge cannot see
    the score: on circle packing the hand-authored ``validation_details``
    embeds ``sum_radii``, and ``metrics`` carries its running mean and max.

    That leak is left in place deliberately. Excising score-shaped values from
    arbitrary nested diagnostics is not possible in general, and attempting it
    would strip real evidence -- "valid: false" is exactly what a judge needs.
    More to the point, the comparison is against an ASI arm whose feedback
    contains the score prominently; blinding only our arm would handicap it on
    a dimension the experiment is not testing. The narrower property we do
    enforce -- no labelled ``scores`` block -- is what stops the judge
    labelling straight off the verdict.

    (With ``RefinerConfig`` enabled a ``refiner_prompt`` parameter is
    auto-injected and co-evolved, so the candidate becomes a two-key dict. The
    judge's component vocabulary follows whatever the candidate actually has.)
    """
    skip = set(skip_keys)
    sections: list[str] = []
    for key, value in side_info.items():
        if key in skip:
            continue
        rendered = _describe(value)
        if rendered:
            sections.append(f"[{key.upper()}]\n{rendered}")
    # A plain string, not a mapping. build_trace JSON-dumps an unsegmented
    # mapping wholesale into fallback_text, which would put the trace id and a
    # second copy of the task in front of the judge as if they were evidence.
    return build_trace("\n\n".join(sections), trace_id=trace_id, task=task, metadata=metadata)


@dataclass
class ArmedEvaluator:
    """Wraps an example's ``evaluate`` and rewrites what feedback it emits.

    The wrapped callable keeps the inner evaluator's *signature contract*:
    ``optimize_anything`` inspects the evaluator to decide which kwargs to pass
    (``example``, ``opt_state``), so this forwards only what the inner function
    declares. Accepting ``**kwargs`` blindly and passing everything through
    would hand ``example`` to a single-task evaluator that does not take one.
    """

    inner: Callable[..., Any]
    arm: str
    #: Required for TAXONOMY. Any object with ``judge(traces) -> {id: [Occurrence]}``.
    judge: Any | None = None
    #: STOCK only. Where taxonomy-generation traces accumulate.
    sink: TraceSink | None = None
    task_text: str = ""
    #: Rendered into the trace but never shown as its own judge section.
    skip_keys: Sequence[str] = ("scores",)

    #: Seconds to allow one evaluation before scoring it 0 and moving on.
    #: None disables the bound.
    #:
    #: Needed because an evaluator may execute LLM-written code. CloudCast's
    #: ``run_evaluation`` imports the candidate and calls it in-process, guarded
    #: only by ``except Exception`` -- and a non-terminating loop is not an
    #: exception. An evolved routing algorithm that fails to terminate therefore
    #: hangs the whole run silently: no error, no output, and no *spend*, so a
    #: dollar-budget stopper can never fire either. Observed once: 88 minutes
    #: pinned at one core with the progress bar frozen mid-run.
    #:
    #: Circle packing does not need this -- its example already runs candidates
    #: in a subprocess under a time limit -- but the bound is harmless there.
    timeout_s: float | None = None

    evaluations: int = 0
    judged: int = 0
    judge_failures: int = 0
    occurrences_emitted: int = 0
    timeouts: int = 0
    #: Threads abandoned to a non-terminating candidate. Python cannot kill a
    #: thread, so a timed-out evaluation keeps burning a core until the process
    #: exits. Counted rather than hidden: a rising number means the run is
    #: losing CPU and the cap should be lowered or the arm abandoned.
    leaked_workers: int = 0
    _counter: int = 0
    _lock: threading.Lock = field(default_factory=threading.Lock, repr=False)

    def __post_init__(self) -> None:
        if self.arm not in ARMS:
            raise ValueError(f"arm must be one of {ARMS}, got {self.arm!r}")
        if self.arm == TAXONOMY and self.judge is None:
            raise ValueError(
                "the taxonomy arm needs a judge; without one it would silently "
                "degrade to score-only and the run would be mislabelled"
            )
        self._accepted = _accepted_params(self.inner)
        # Mirror the inner signature so gepa's own inspection sees the same
        # contract it would have seen without this wrapper.
        self.__signature__ = inspect.signature(self.inner)

    def __call__(self, candidate: Any, **kwargs: Any) -> tuple[float, dict[str, Any]]:
        forwarded = kwargs if self._accepted is None else {k: v for k, v in kwargs.items() if k in self._accepted}

        if self.timeout_s is None:
            result = self.inner(candidate, **forwarded)
        else:
            # A raw DAEMON thread, not ThreadPoolExecutor. Pool threads are
            # non-daemon, so the interpreter joins them at shutdown -- one
            # abandoned candidate would hang the process forever at exit, having
            # already cost the run nothing but a core. Daemon threads are killed
            # when the process ends, which is the only way to be rid of a loop
            # Python cannot interrupt.
            #
            # One thread per call rather than a shared pool: a pool would be
            # permanently poisoned by the first non-terminating candidate, since
            # the abandoned worker never returns its slot.
            box: dict[str, Any] = {}

            def _run() -> None:
                try:
                    box["value"] = self.inner(candidate, **forwarded)
                except BaseException as exc:  # re-raised on the calling thread
                    box["error"] = exc

            worker = threading.Thread(target=_run, daemon=True)
            worker.start()
            worker.join(self.timeout_s)

            if worker.is_alive():
                with self._lock:
                    self.timeouts += 1
                    self.leaked_workers += 1
                    self.evaluations += 1
                # Scored 0 and reported as a normal failed evaluation. The
                # optimizer must SEE the failure -- a candidate that does not
                # terminate is a bad candidate, and telling reflection so is the
                # whole point. Raising here would abort the run instead.
                return 0.0, {
                    "scores": {},
                    "error": (
                        f"evaluation exceeded {self.timeout_s:.0f}s and was abandoned. "
                        "The candidate did not terminate."
                    ),
                }
            if "error" in box:
                raise box["error"]
            result = box["value"]

        if isinstance(result, tuple):
            score, side_info = result
            side_info = dict(side_info or {})
        else:
            score, side_info = result, {}

        with self._lock:
            self.evaluations += 1
            index = self._counter
            self._counter += 1
        trace_id = f"eval-{index:05d}"

        if self.arm == STOCK:
            if self.sink is not None:
                # ``score`` goes in the metadata here but NOT into the judge's
                # view (see _judge). Generation and judging want opposite
                # things: AdaMAST benefits from knowing which trajectories went
                # badly when drafting codes, while a judge shown the verdict can
                # label by outcome instead of by evidence. The proven
                # base_val.traces.jsonl carries metadata.score, so this also
                # keeps the format identical to the one already generated from.
                self.sink.write(
                    trace_from_side_info(
                        side_info,
                        trace_id=trace_id,
                        task=self.task_text,
                        skip_keys=self.skip_keys,
                        metadata={"score": score},
                    )
                )
            return score, side_info

        preserved = {k: side_info[k] for k in PRESERVED_KEYS if k in side_info}

        if self.arm == SCORE_ONLY:
            return score, preserved

        trace = trace_from_side_info(side_info, trace_id=trace_id, task=self.task_text, skip_keys=self.skip_keys)
        occurrences = self._judge(trace)
        if occurrences:
            preserved[FAILURE_MODES_KEY] = [o.for_reflection() for o in occurrences]
        return score, preserved

    # -- internals --------------------------------------------------------

    def _judge(self, trace: SegmentedTrace) -> list[Occurrence]:
        """Diagnose one trace. Fail-soft: a lost diagnosis must not cost a run.

        A failure here yields no occurrences, which makes that single
        evaluation look like the score-only arm. That is the right trade -- the
        alternative is killing a paid run over one judge timeout -- but the
        counter is reported so a run with many failures is not read as a clean
        taxonomy result.
        """
        try:
            results = self.judge.judge([trace])
        except Exception:
            with self._lock:
                self.judge_failures += 1
            return []
        found = list(results.get(trace.trace_id) or [])
        with self._lock:
            self.judged += 1
            self.occurrences_emitted += len(found)
        return found

    def summary(self) -> dict[str, Any]:
        out: dict[str, Any] = {
            "arm": self.arm,
            "evaluations": self.evaluations,
        }
        if self.arm == STOCK:
            out["traces_written"] = self.sink.written if self.sink else 0
        if self.timeout_s is not None:
            out["timeouts"] = self.timeouts
            out["leaked_workers"] = self.leaked_workers
        if self.arm == TAXONOMY:
            out["traces_judged"] = self.judged
            out["judge_failures"] = self.judge_failures
            out["occurrences_emitted"] = self.occurrences_emitted
            if self.evaluations:
                out["occurrences_per_evaluation"] = round(self.occurrences_emitted / self.evaluations, 3)
        return out


def _accepted_params(fn: Callable[..., Any]) -> set[str] | None:
    """Parameter names ``fn`` accepts, or None when it takes ``**kwargs``."""
    signature = inspect.signature(fn)
    if any(p.kind == inspect.Parameter.VAR_KEYWORD for p in signature.parameters.values()):
        return None
    return set(signature.parameters)
